using System.ComponentModel;

namespace CryptoScanner.Services;

/// <summary>
/// Simple localization service with German (de) and English (en) dictionaries.
/// Access via Loc.T("key") or Loc["key"].
/// </summary>
public sealed class Loc : INotifyPropertyChanged
{
    private static string _lang = "de";
    public static Loc Instance { get; } = new();
    public static event Action? LanguageChanged;
    public event PropertyChangedEventHandler? PropertyChanged;

    private Loc() { }

    public static string Language
    {
        get => _lang;
        set
        {
            if (_lang == value) return;
            _lang = value;
            SavePreference(value);
            Instance.RaiseLanguageChanged();
            LanguageChanged?.Invoke();
        }
    }

    public static string T(string key) => Get(key);
    public string this[string key] => Get(key);

    public static string Get(string key)
    {
        var dict = _lang == "en" ? En : De;
        return dict.TryGetValue(key, out var val) ? val : key;
    }

    static Loc()
    {
        // Load saved preference
        try
        {
            var path = PreferencePath();
            if (File.Exists(path))
            {
                var saved = File.ReadAllText(path).Trim();
                if (saved is "de" or "en") _lang = saved;
            }
        }
        catch { }
    }

    private static void SavePreference(string lang)
    {
        try
        {
            var dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "CryptoScanner");
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "language.txt"), lang);
        }
        catch { }
    }

    private static string PreferencePath() =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "CryptoScanner", "language.txt");

    private void RaiseLanguageChanged()
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
    }

    // ═══════════════════════════════════════════════════════════
    // GERMAN
    // ═══════════════════════════════════════════════════════════
    private static readonly Dictionary<string, string> De = new()
    {
        // Tabs
        ["tab.scanner"] = "Scanner",
        ["tab.depot"] = "Depot",
        ["tab.ai"] = "KI-Trading",
        ["tab.strategy"] = "Strategie",

        // Scanner toolbar
        ["scan.start"] = "Scan Starten",
        ["scan.stop"] = "Abbrechen",
        ["scan.start.tip"] = "Alle Coins scannen und technisch analysieren",
        ["scan.stop.tip"] = "Laufenden Scan abbrechen",
        ["search.tip"] = "Nach Coin-Name oder Symbol suchen",
        ["filter.tip"] = "Nur Coins mit bestimmtem Signal anzeigen",
        ["sort.tip"] = "Tabelle nach gewaehltem Kriterium sortieren",
        ["timeframe.tip"] = "Zeitraum fuer OHLC-Daten und technische Analyse",
        ["currency.tip"] = "Handelswaehrung auswaehlen (USD oder EUR)",
        ["autorefresh.tip"] = "Automatisch in regelmaessigen Abstaenden neu scannen",
        ["interval.tip"] = "Intervall fuer automatische Aktualisierung",

        // DataGrid columns
        ["col.coin"] = "COIN",
        ["col.price"] = "PREIS",
        ["col.change"] = "24H %",
        ["col.score"] = "SCORE",
        ["col.signal"] = "SIGNAL",
        ["col.volume"] = "VOLUMEN",
        ["col.buyzone"] = "KAUFZONE",
        ["col.mystrategy"] = "MEINE STRATEGIE",
        ["col.invested"] = "INVESTIERT",
        ["col.current"] = "AKTUELL",
        ["col.value"] = "WERT",
        ["col.pnlshort"] = "G/V",
        ["col.fee"] = "GEBUEHR",
        ["col.source"] = "QUELLE",
        ["col.setup"] = "SETUP",
        ["col.returnshort"] = "RENDITE",
        ["col.drawdown"] = "DD",
        ["col.coin.tip"] = "Kryptowaehrung / Handelspaar",
        ["col.price.tip"] = "Aktueller Marktpreis",
        ["col.change.tip"] = "Preisaenderung in den letzten 24 Stunden",
        ["col.score.tip"] = "Composite-Score basierend auf technischen Indikatoren (-100 bis +100)",
        ["col.signal.tip"] = "Handelssignal basierend auf dem Composite-Score",
        ["col.volume.tip"] = "Handelsvolumen in den letzten 24 Stunden",

        // Signals
        ["signal.strongbuy"] = "Starker Kauf",
        ["signal.buy"] = "Kauf",
        ["signal.hold"] = "Halten",
        ["signal.sell"] = "Verkauf",
        ["signal.strongsell"] = "Starker Verkauf",

        // Detail panel
        ["detail.score"] = "Bewertung",
        ["detail.indicators"] = "Technische Indikatoren",
        ["detail.pricerange"] = "Preisspanne",
        ["detail.pricoverview"] = "Preisuebersicht",
        ["detail.orderbook"] = "Orderbuch (Kauf-/Verkaufsdruck)",

        // Indicators with tooltips
        ["rsi.label"] = "RSI (14)",
        ["rsi.tip"] = "Relative Strength Index (14 Perioden)\n< 30 = Ueberverkauft (Kaufsignal)\n> 70 = Ueberkauft (Verkaufssignal)",
        ["macd.label"] = "MACD",
        ["macd.tip"] = "Moving Average Convergence Divergence\nPositiv = Aufwaertstrend\nNegativ = Abwaertstrend",
        ["sma.label"] = "SMA 20/50",
        ["sma.tip"] = "Simple Moving Average\nSMA20 = kurzfristiger Durchschnitt\nSMA50 = mittelfristiger Durchschnitt",
        ["ema.tip"] = "Exponential Moving Average\nReagiert schneller auf Preisaenderungen als SMA",
        ["bollinger.label"] = "Bollinger",
        ["bollinger.tip"] = "Bollinger Band (20 Perioden, 2 Std.abw.)\nNahe oberem Band = moeglicherweise ueberkauft\nNahe unterem Band = moeglicherweise ueberverkauft",
        ["volume.label"] = "Volumen",
        ["volume.tip"] = "Handelsvolumen im Vergleich zum Durchschnitt",
        ["range.tip"] = "Position des aktuellen Preises zwischen Hoch und Tief\n0% = am Tief, 100% = am Hoch",
        ["orderbook.tip"] = "Live-Orderbuchdaten von Kraken\nZeigt das Verhaeltnis von Kaeufern zu Verkaeufern",
        ["bid.tip"] = "Anteil der Kaufauftraege am gesamten Ordervolumen",
        ["ask.tip"] = "Anteil der Verkaufsauftraege am gesamten Ordervolumen",

        // Chart toggles
        ["chart.candles"] = "Kerzen",
        ["chart.candles.tip"] = "Zwischen Linien- und Kerzenchart umschalten",
        ["chart.sma20.tip"] = "Simple Moving Average 20 Perioden (kurzfristig)",
        ["chart.sma50.tip"] = "Simple Moving Average 50 Perioden (mittelfristig)",
        ["chart.ema12.tip"] = "Exponential Moving Average 12 Perioden",
        ["chart.ema26.tip"] = "Exponential Moving Average 26 Perioden",
        ["chart.bb.tip"] = "Bollinger Baender (20 Perioden, 2 Std.abw.)",

        // Depot
        ["depot.balance"] = "Kontostand",
        ["depot.balance.tip"] = "Verfuegbares Barguthaben fuer neue Kaeufe",
        ["depot.totalvalue"] = "Gesamtwert",
        ["depot.totalvalue.tip"] = "Barguthaben + Wert aller gehaltenen Positionen",
        ["depot.pnl"] = "Gewinn/Verlust",
        ["depot.pnl.tip"] = "Gesamtgewinn oder -verlust seit Depotstart",
        ["depot.return"] = "Rendite",
        ["depot.return.tip"] = "Prozentuale Rendite seit Depotstart",
        ["depot.startcapital"] = "Startkapital",
        ["depot.startcapital.tip"] = "Anfangskapital fuer das Uebungsdepot eingeben",
        ["depot.reset"] = "Depot Zuruecksetzen",
        ["depot.reset.tip"] = "Alle Positionen und Transaktionen loeschen und mit neuem Startkapital beginnen",
        ["depot.positions"] = "Positionen",
        ["depot.history"] = "Transaktionshistorie",
        ["buy"] = "Kaufen",
        ["buy.tip"] = "Diese Kryptowaehrung zum aktuellen Preis kaufen",
        ["sell"] = "Verkaufen",
        ["sell.tip"] = "Diese Position zum aktuellen Preis verkaufen",

        // AI Trading
        ["ai.provider"] = "Anbieter",
        ["ai.provider.tip"] = "KI-Anbieter fuer automatische Handelsempfehlungen",
        ["ai.apikey"] = "API-Schluessel",
        ["ai.apikey.tip"] = "API-Schluessel fuer den gewaehlten KI-Anbieter\n(wird verschluesselt gespeichert)",
        ["ai.apiurl"] = "API-URL",
        ["ai.apiurl.tip"] = "API-Endpunkt URL (Standard wird automatisch gesetzt)",
        ["ai.analyze"] = "KI-Analyse Starten",
        ["ai.analyze.tip"] = "KI analysiert alle gescannten Coins und erstellt Handelsempfehlungen",
        ["ai.execall"] = "Alle Ausfuehren",
        ["ai.autotrading"] = "Auto-Trading (nach Scan)",
        ["ai.autotrading.tip"] = "KI handelt automatisch nach jedem Scan basierend auf den Empfehlungen",
        ["ai.settings"] = "KI-Trading Einstellungen",
        ["ai.recommendations"] = "KI-Empfehlungen",
        ["ai.log"] = "KI-Protokoll",
        ["ai.norule"] = "Ohne API-Schluessel wird der regelbasierte Modus verwendet (technische Indikatoren).",

        // Strategy
        ["strat.name.tip"] = "Name der Strategie (wird beim Speichern verwendet)",
        ["strat.condition"] = "Bedingung:",
        ["strat.action"] = "Aktion:",
        ["strat.rsi.tip"] = "Erstellt eine RSI-Bedingung (z.B. RSI < 30 = ueberverkauft)",
        ["strat.macd.tip"] = "Erstellt eine MACD-Bedingung (Signal, Kreuzung)",
        ["strat.sma.tip"] = "Erstellt eine Preisvergleich-Bedingung mit SMA",
        ["strat.ema.tip"] = "Erstellt eine Preisvergleich-Bedingung mit EMA",
        ["strat.bb.tip"] = "Erstellt eine Bollinger-Band-Bedingung",
        ["strat.vol.tip"] = "Erstellt eine Volumen-Bedingung (ueber/unter Durchschnitt)",
        ["strat.score.tip"] = "Erstellt eine Composite-Score-Bedingung",
        ["strat.buy.tip"] = "Kaufaktion hinzufuegen (Prozent des Guthabens)",
        ["strat.sell.tip"] = "Verkaufaktion hinzufuegen (Prozent der Position)",
        ["strat.hold.tip"] = "Halteaktion hinzufuegen (keine Transaktion)",
        ["strat.save"] = "Speichern",
        ["strat.save.tip"] = "Aktuelle Strategie als JSON speichern",
        ["strat.new"] = "Neu",
        ["strat.test"] = "Testen",
        ["strat.test.tip"] = "Strategie gegen aktuelle Scan-Daten testen (kein echter Handel)",
        ["strat.active"] = "Aktiv",
        ["strat.active.tip"] = "Strategie nach jedem Scan automatisch ausfuehren",
        ["strat.load"] = "Laden",
        ["strat.load.tip"] = "Gespeicherte Strategie laden",
        ["strat.results"] = "Strategie-Ergebnisse",
        ["strat.log"] = "Protokoll",
        ["strat.execall"] = "Alle ausfuehren",
        ["execute"] = "Ausfuehren",

        // General
        ["status.ready"] = "Bereit",
        ["status.lastupdate"] = "Update:",
        ["status.never"] = "Nie",
        ["close"] = "Schliessen",
        ["cancel"] = "Abbrechen",
        ["save"] = "Speichern",
        ["all"] = "Alles",
        ["yes"] = "Ja",
        ["no"] = "Nein",
        ["amount"] = "Menge",
        ["price"] = "Preis",
        ["value"] = "Wert",
        ["operator"] = "Operator",
        ["preset"] = "Preset (optional)",
        ["alarmtext"] = "Alarmtext",
        ["percentshare"] = "Prozent / Anteil",
        ["total"] = "Gesamt",
        ["date"] = "Datum",
        ["type"] = "Typ",
        ["source"] = "Quelle",
        ["confidence"] = "Konfidenz",
        ["reason"] = "Begruendung",
        ["action"] = "Aktion",
        ["language"] = "DE",
        ["help"] = "Hilfe",
        ["help.button"] = "? Hilfe",
        ["help.subtitle"] = "So benutzt du CryptoScanner am einfachsten.",
        ["welcome.title"] = "CRYPTO SCANNER",
        ["welcome.subtitle"] = "Technische Analyse und Trading",
        ["welcome.notice.title"] = "WICHTIGER HINWEIS",
        ["welcome.notice.1"] = "Diese Software dient ausschliesslich zu Informations- und Unterhaltungszwecken. Die bereitgestellten Analysen, Signale und Empfehlungen stellen keine Anlageberatung dar.",
        ["welcome.notice.2"] = "Der Handel mit Kryptowaehrungen ist mit erheblichen Risiken verbunden. Sie koennen Ihr gesamtes eingesetztes Kapital verlieren.",
        ["welcome.notice.3"] = "Jegliche Haftung fuer finanzielle Verluste, die durch die Nutzung dieser Software entstehen, wird ausdruecklich ausgeschlossen.",
        ["welcome.notice.4"] = "Handeln Sie stets eigenverantwortlich und investieren Sie nur Geld, dessen Verlust Sie sich leisten koennen.",
        ["welcome.accept"] = "Ich habe den Hinweis gelesen und verstanden",
        ["welcome.continue"] = "Weiter",
        ["help.quickstart.title"] = "1. Schnellstart",
        ["help.quickstart.1"] = "Waehle oben die Waehrung und den Zeitraum. Klicke dann auf 'Scan Starten'.",
        ["help.quickstart.2"] = "Links erscheint die Coin-Liste. Klicke auf einen Coin, um rechts das Diagramm und die Details zu sehen.",
        ["help.scanner.title"] = "2. Scanner: Leiste, Buttons und Spalten",
        ["help.scanner.1"] = "Scan Starten: Laedt Handelspaare, Preise und OHLC-Daten neu.",
        ["help.scanner.2"] = "Abbrechen: Stoppt den aktuellen Scan.",
        ["help.scanner.3"] = "Waehrung: Waehlt USD oder EUR fuer Scanner und Depot.",
        ["help.scanner.4"] = "Suchen: Filtert die Liste nach Coin-Name oder Symbol.",
        ["help.scanner.5"] = "Filter: Zeigt nur Coins mit dem ausgewaehlten Scanner-Signal.",
        ["help.scanner.6"] = "Sortierung und A/Z: Sortiert die Tabelle auf- oder absteigend.",
        ["help.scanner.7"] = "Zeitraum: Bestimmt Diagramm und Analysefenster wie 24h, 7 Tage, 1 Monat, 3 Monate oder 1 Jahr.",
        ["help.scanner.8"] = "Auto und Intervall: Startet automatisch neue Scans.",
        ["help.scanner.9"] = "COIN: Name des Basiswerts. PREIS: letzter bekannter Marktpreis. 24H %: Preisveraenderung der letzten 24 Stunden.",
        ["help.scanner.10"] = "SCORE: Gesamtscore aus mehreren Indikatoren. SIGNAL: daraus abgeleitete Scanner-Empfehlung.",
        ["help.scanner.11"] = "MEINE STRATEGIE: Was deine aktive Strategie fuer diesen Coin tun wuerde.",
        ["help.scanner.12"] = "Kaufen-Button: Oeffnet den Kaufdialog fuer Paper-Trading.",
        ["help.detail.title"] = "3. Detailbereich und Diagramm",
        ["help.detail.1"] = "Das eigentliche Gesamtergebnis ist immer der Score mit dem farbigen Signal.",
        ["help.detail.2"] = "Einzelindikatoren wie RSI oder Bollinger koennen neutral sein, auch wenn das Gesamtsignal auf Kauf steht.",
        ["help.detail.3"] = "Mit 'Kerzen' wechselst du zwischen Linien- und Kerzendarstellung.",
        ["help.detail.4"] = "SMA 20, SMA 50, EMA 12, EMA 26 und BB blenden Zusatzlinien ein oder aus.",
        ["help.detail.5"] = "Mit dem Mausrad kannst du zoomen, mit gedrueckter linker Maustaste verschieben und per Doppelklick zuruecksetzen.",
        ["help.detail.6"] = "Wenn du mit der Maus ueber das Diagramm faehrst, siehst du Preis, Zeit und OHLC-Werte.",
        ["help.detail.7"] = "Orderbuch zeigt den aktuellen Kauf- und Verkaufsdruck, falls Daten geladen wurden.",
        ["help.depot.title"] = "4. Depot",
        ["help.depot.1"] = "Startkapital: Betrag, mit dem dein Paper-Trading beginnt.",
        ["help.depot.2"] = "Depot Zuruecksetzen: Setzt Positionen und Verlauf auf das Startkapital zurueck.",
        ["help.depot.3"] = "Positionen-Tabelle: Zeigt Coin, Menge, Kaufpreis, aktuellen Kurs, Gesamtwert und Gewinn/Verlust.",
        ["help.depot.4"] = "Verkaufen-Button: Oeffnet den Verkaufsdialog fuer die gewaehlte Position.",
        ["help.depot.5"] = "Transaktionshistorie: Zeigt Datum, Coin, Typ, Menge, Preis, Gesamt und Quelle eines Trades.",
        ["help.ai.title"] = "5. KI-Trading",
        ["help.ai.1"] = "Anbieter: Waehlt den KI-Dienst. API-Schluessel: Zugangsschluessel. API-URL: Endpunkt des Dienstes.",
        ["help.ai.2"] = "KI-Analyse Starten: Erstellt neue Empfehlungen aus aktuellen Scan-Daten.",
        ["help.ai.3"] = "Alle Ausfuehren: Fuehrt alle angezeigten KI-Empfehlungen als Paper-Trades aus.",
        ["help.ai.4"] = "Auto-Trading: Startet die KI-Analyse automatisch nach jedem Scan.",
        ["help.ai.5"] = "Empfehlungstabelle: Zeigt Coin, Aktion, Menge, Konfidenz und Begruendung.",
        ["help.ai.6"] = "Ausfuehren-Button: Fuehrt nur die jeweilige Empfehlung aus.",
        ["help.ai.7"] = "KI-Protokoll: Verlauf der Analysen und eventueller Fehler.",
        ["help.strategy.title"] = "6. Strategie",
        ["help.strategy.1"] = "Strategie-Name: Name deiner aktuellen Strategie.",
        ["help.strategy.2"] = "RSI, MACD, SMA, EMA, BB, Vol, Score: Fuegen neue Bedingungsbloecke hinzu.",
        ["help.strategy.3"] = "Kaufen, Verkaufen, Halten: Fuegen Aktionsbloecke hinzu.",
        ["help.strategy.4"] = "Speichern, Neu, Testen: Strategie sichern, neu beginnen oder gegen aktuelle Scan-Daten pruefen.",
        ["help.strategy.5"] = "Aktiv: Wendet die Strategie nach jedem Scan automatisch auf alle Coins an.",
        ["help.strategy.6"] = "Zentrieren und Loeschen: Arbeitsflaeche ordnen oder ausgewaehlten Block entfernen.",
        ["help.strategy.7"] = "Gespeicherte Strategien und Laden: Oeffnet eine vorhandene Strategie im Editor.",
        ["help.strategy.8"] = "Strategie-Ergebnisse: Zeigt Coin, Aktion, Menge und Grund fuer den letzten Test.",
        ["help.strategy.9"] = "Alle ausfuehren und Ausfuehren: Fuehren vorgeschlagene Strategie-Trades als Paper-Trades aus.",
        ["help.strategy.10"] = "Protokoll: Verlauf deiner Strategietests und Ausfuehrungen.",
        ["help.trade.title"] = "7. Kauf- und Verkaufsfenster",
        ["help.trade.1"] = "Anzahl Coins oder Betrag in Waehrung: Bestimmt, wie du kaufen willst.",
        ["help.trade.2"] = "Alles: Setzt den maximal moeglichen Betrag oder die ganze Position ein.",
        ["help.trade.3"] = "Vorschau: Zeigt vorab, was dein Eintrag bedeutet.",
        ["help.trade.4"] = "Kaufen oder Verkaufen: Fuehrt den Paper-Trade aus. Abbrechen schliesst das Fenster ohne Aenderung.",
        ["search.watermark"] = "Suchen...",
        ["scan.currency.tip"] = "Handelswaehrung auswaehlen (USD oder EUR)",
        ["sort.direction"] = "A/Z",
        ["sort.direction.tip"] = "Sortierrichtung umkehren (aufsteigend/absteigend)",
        ["strategy.applyfake"] = "Jetzt auf Fake-Depot anwenden",
        ["strategy.autofake"] = "Nach jedem Scan automatisch handeln",
        ["strategy.autocalc"] = "Strategie automatisch berechnen",
        ["strategy.optimizing.note"] = "Nutze das als Vorschlag, nicht als vollautomatisches Lernen.",
        ["strategy.applyoptimized"] = "Uebern.",
        ["strategy.load.saved.tip"] = "Gespeicherte Strategie zum Laden auswaehlen",
        ["portfolio.sort"] = "Sortieren:",
        ["portfolio.exportpdf"] = "Als PDF",
        ["portfolio.resetview"] = "Reset Ansicht",
        ["portfolio.chart"] = "Depot-Entwicklung",
        ["portfolio.savepdf.title"] = "Depotliste als PDF speichern",
        ["portfolio.savepdf.type"] = "PDF-Datei",
        ["buy.dialog.title"] = "Coin Kaufen",
        ["sell.dialog.title"] = "Coin Verkaufen",
        ["buy.mode.amount"] = "Anzahl Coins",
        ["buy.mode.value"] = "Betrag in Waehrung",
        ["buy.amount.watermark"] = "Menge (z.B. 0.01)",
        ["buy.value.watermark"] = "Betrag (z.B. 500)",
        ["sell.amount.watermark"] = "Menge zum Verkaufen",
        ["editblock.hint"] = "Hier kannst du die wichtigste Logik des Blocks direkt aendern.",
        ["editblock.amount.hint"] = "Beispiele: 5%, 10%, 25%, 50%, 100% oder Alles",
        ["editblock.operator.tip"] = "Vergleichsoperator fuer die Bedingung",
        ["editblock.value.watermark"] = "z.B. 30",
        ["editblock.preset.watermark"] = "z.B. Signal positiv",
        ["editblock.alarm.watermark"] = "Signal erkannt",
        ["source.manual"] = "Manuell",
        ["source.ai"] = "KI-Trading",
        ["source.strategy"] = "Strategie",
        ["source.backtest"] = "Backtest",
        ["orderbook.strongbuy"] = "Starker Kaufdruck",
        ["orderbook.buy"] = "Kaufdruck",
        ["orderbook.neutral"] = "Neutral",
        ["orderbook.sell"] = "Verkaufsdruck",
        ["orderbook.strongsell"] = "Starker Verkaufsdruck",
        ["ti.rsi.oversold"] = "Ueberverkauft",
        ["ti.rsi.low"] = "Niedrig",
        ["ti.rsi.neutral"] = "Neutral",
        ["ti.rsi.high"] = "Hoch",
        ["ti.rsi.overbought"] = "Ueberkauft",
        ["ti.macd.bullish"] = "Bullisch",
        ["ti.macd.softbullish"] = "Leicht Bullisch",
        ["ti.macd.bearish"] = "Baerisch",
        ["ti.macd.softbearish"] = "Leicht Baerisch",
        ["ti.bb.strongoversold"] = "Stark Ueberverkauft",
        ["ti.bb.oversold"] = "Ueberverkauft",
        ["ti.bb.overbought"] = "Ueberkauft",
        ["ti.bb.strongoverbought"] = "Stark Ueberkauft",
        ["ti.sma.golden"] = "Bullisch (Golden Cross)",
        ["ti.sma.death"] = "Baerisch (Death Cross)",
        ["ti.volume.above"] = "Ueberdurchschnittlich",
        ["ti.volume.below"] = "Unterdurchschnittlich",
        ["strategy.block.start"] = "START",
        ["strategy.block.startdesc"] = "Einstiegspunkt (1 Ausgang)",
        ["strategy.block.buy"] = "KAUFEN",
        ["strategy.block.sell"] = "VERKAUFEN",
        ["strategy.block.hold"] = "HALTEN",
        ["strategy.block.alarm"] = "ALARM",
        ["strategy.block.buydesc"] = "Kaufen: {0}",
        ["strategy.block.selldesc"] = "Verkaufen: {0}",
        ["strategy.block.holddesc"] = "Position halten",
        ["strategy.block.alarmdesc"] = "Benachrichtigung",
        ["strategy.name.new"] = "Neue Strategie",
        ["strategy.action.detected"] = "Signal erkannt",
        ["buyzone.nobuy"] = "Nicht kaufen",
        ["buyzone.now"] = "Jetzt ({0})",
        ["buyzone.below"] = "Unter {0}",
        ["strategy.action.buy"] = "Kaufen",
        ["strategy.action.sell"] = "Verkaufen",
        ["strategy.action.hold"] = "Halten",
    };

    // ═══════════════════════════════════════════════════════════
    // ENGLISH
    // ═══════════════════════════════════════════════════════════
    private static readonly Dictionary<string, string> En = new()
    {
        ["tab.scanner"] = "Scanner",
        ["tab.depot"] = "Portfolio",
        ["tab.ai"] = "AI Trading",
        ["tab.strategy"] = "Strategy",

        ["scan.start"] = "Start Scan",
        ["scan.stop"] = "Cancel",
        ["scan.start.tip"] = "Scan all coins and run technical analysis",
        ["scan.stop.tip"] = "Cancel the running scan",
        ["search.tip"] = "Search by coin name or symbol",
        ["filter.tip"] = "Show only coins with a specific signal",
        ["sort.tip"] = "Sort the table by selected criteria",
        ["timeframe.tip"] = "Timeframe for OHLC data and technical analysis",
        ["currency.tip"] = "Select trading currency (USD or EUR)",
        ["autorefresh.tip"] = "Automatically rescan at regular intervals",
        ["interval.tip"] = "Interval for automatic refresh",

        ["col.coin"] = "COIN",
        ["col.price"] = "PRICE",
        ["col.change"] = "24H %",
        ["col.score"] = "SCORE",
        ["col.signal"] = "SIGNAL",
        ["col.volume"] = "VOLUME",
        ["col.buyzone"] = "BUY ZONE",
        ["col.mystrategy"] = "MY STRATEGY",
        ["col.invested"] = "INVESTED",
        ["col.current"] = "CURRENT",
        ["col.value"] = "VALUE",
        ["col.pnlshort"] = "P/L",
        ["col.fee"] = "FEE",
        ["col.source"] = "SOURCE",
        ["col.setup"] = "SETUP",
        ["col.returnshort"] = "RETURN",
        ["col.drawdown"] = "DD",
        ["col.coin.tip"] = "Cryptocurrency / trading pair",
        ["col.price.tip"] = "Current market price",
        ["col.change.tip"] = "Price change in the last 24 hours",
        ["col.score.tip"] = "Composite score based on technical indicators (-100 to +100)",
        ["col.signal.tip"] = "Trading signal based on the composite score",
        ["col.volume.tip"] = "Trading volume in the last 24 hours",

        ["signal.strongbuy"] = "Strong Buy",
        ["signal.buy"] = "Buy",
        ["signal.hold"] = "Hold",
        ["signal.sell"] = "Sell",
        ["signal.strongsell"] = "Strong Sell",

        ["detail.score"] = "Rating",
        ["detail.indicators"] = "Technical Indicators",
        ["detail.pricerange"] = "Price Range",
        ["detail.pricoverview"] = "Price Overview",
        ["detail.orderbook"] = "Order Book (Buy/Sell Pressure)",

        ["rsi.label"] = "RSI (14)",
        ["rsi.tip"] = "Relative Strength Index (14 periods)\n< 30 = Oversold (buy signal)\n> 70 = Overbought (sell signal)",
        ["macd.label"] = "MACD",
        ["macd.tip"] = "Moving Average Convergence Divergence\nPositive = Uptrend\nNegative = Downtrend",
        ["sma.label"] = "SMA 20/50",
        ["sma.tip"] = "Simple Moving Average\nSMA20 = short-term average\nSMA50 = medium-term average",
        ["ema.tip"] = "Exponential Moving Average\nReacts faster to price changes than SMA",
        ["bollinger.label"] = "Bollinger",
        ["bollinger.tip"] = "Bollinger Bands (20 periods, 2 std dev)\nNear upper band = possibly overbought\nNear lower band = possibly oversold",
        ["volume.label"] = "Volume",
        ["volume.tip"] = "Trading volume compared to average",
        ["range.tip"] = "Current price position between high and low\n0% = at low, 100% = at high",
        ["orderbook.tip"] = "Live order book data from Kraken\nShows the ratio of buyers to sellers",
        ["bid.tip"] = "Share of buy orders in total order volume",
        ["ask.tip"] = "Share of sell orders in total order volume",

        ["chart.candles"] = "Candles",
        ["chart.candles.tip"] = "Toggle between line and candlestick chart",
        ["chart.sma20.tip"] = "Simple Moving Average 20 periods (short-term)",
        ["chart.sma50.tip"] = "Simple Moving Average 50 periods (medium-term)",
        ["chart.ema12.tip"] = "Exponential Moving Average 12 periods",
        ["chart.ema26.tip"] = "Exponential Moving Average 26 periods",
        ["chart.bb.tip"] = "Bollinger Bands (20 periods, 2 std dev)",

        ["depot.balance"] = "Balance",
        ["depot.balance.tip"] = "Available cash balance for new purchases",
        ["depot.totalvalue"] = "Total Value",
        ["depot.totalvalue.tip"] = "Cash balance + value of all held positions",
        ["depot.pnl"] = "Profit/Loss",
        ["depot.pnl.tip"] = "Total profit or loss since portfolio start",
        ["depot.return"] = "Return",
        ["depot.return.tip"] = "Percentage return since portfolio start",
        ["depot.startcapital"] = "Starting Capital",
        ["depot.startcapital.tip"] = "Enter starting capital for the practice portfolio",
        ["depot.reset"] = "Reset Portfolio",
        ["depot.reset.tip"] = "Delete all positions and transactions and start with new capital",
        ["depot.positions"] = "Positions",
        ["depot.history"] = "Transaction History",
        ["buy"] = "Buy",
        ["buy.tip"] = "Buy this cryptocurrency at the current price",
        ["sell"] = "Sell",
        ["sell.tip"] = "Sell this position at the current price",

        ["ai.provider"] = "Provider",
        ["ai.provider.tip"] = "AI provider for automated trade recommendations",
        ["ai.apikey"] = "API Key",
        ["ai.apikey.tip"] = "API key for the selected AI provider\n(stored encrypted)",
        ["ai.apiurl"] = "API URL",
        ["ai.apiurl.tip"] = "API endpoint URL (default is set automatically)",
        ["ai.analyze"] = "Start AI Analysis",
        ["ai.analyze.tip"] = "AI analyzes all scanned coins and creates trade recommendations",
        ["ai.execall"] = "Execute All",
        ["ai.autotrading"] = "Auto-Trading (after scan)",
        ["ai.autotrading.tip"] = "AI trades automatically after each scan based on recommendations",
        ["ai.settings"] = "AI Trading Settings",
        ["ai.recommendations"] = "AI Recommendations",
        ["ai.log"] = "AI Log",
        ["ai.norule"] = "Without an API key, rule-based mode is used (technical indicators).",

        ["strat.name.tip"] = "Strategy name (used when saving)",
        ["strat.condition"] = "Condition:",
        ["strat.action"] = "Action:",
        ["strat.rsi.tip"] = "Create an RSI condition (e.g. RSI < 30 = oversold)",
        ["strat.macd.tip"] = "Create a MACD condition (signal, crossover)",
        ["strat.sma.tip"] = "Create a price comparison condition with SMA",
        ["strat.ema.tip"] = "Create a price comparison condition with EMA",
        ["strat.bb.tip"] = "Create a Bollinger Band condition",
        ["strat.vol.tip"] = "Create a volume condition (above/below average)",
        ["strat.score.tip"] = "Create a composite score condition",
        ["strat.buy.tip"] = "Add buy action (percent of balance)",
        ["strat.sell.tip"] = "Add sell action (percent of position)",
        ["strat.hold.tip"] = "Add hold action (no transaction)",
        ["strat.save"] = "Save",
        ["strat.save.tip"] = "Save current strategy as JSON",
        ["strat.new"] = "New",
        ["strat.test"] = "Test",
        ["strat.test.tip"] = "Test strategy against current scan data (no real trading)",
        ["strat.active"] = "Active",
        ["strat.active.tip"] = "Automatically run strategy after each scan",
        ["strat.load"] = "Load",
        ["strat.load.tip"] = "Load a saved strategy",
        ["strat.results"] = "Strategy Results",
        ["strat.log"] = "Log",
        ["strat.execall"] = "Execute all",
        ["execute"] = "Execute",

        ["status.ready"] = "Ready",
        ["status.lastupdate"] = "Update:",
        ["status.never"] = "Never",
        ["close"] = "Close",
        ["cancel"] = "Cancel",
        ["save"] = "Save",
        ["all"] = "All",
        ["yes"] = "Yes",
        ["no"] = "No",
        ["amount"] = "Amount",
        ["price"] = "Price",
        ["value"] = "Value",
        ["operator"] = "Operator",
        ["preset"] = "Preset (optional)",
        ["alarmtext"] = "Alarm text",
        ["percentshare"] = "Percent / Share",
        ["total"] = "Total",
        ["date"] = "Date",
        ["type"] = "Type",
        ["source"] = "Source",
        ["confidence"] = "Confidence",
        ["reason"] = "Reason",
        ["action"] = "Action",
        ["language"] = "EN",
        ["help"] = "Help",
        ["help.button"] = "? Help",
        ["help.subtitle"] = "How to use CryptoScanner in the easiest way.",
        ["welcome.title"] = "CRYPTO SCANNER",
        ["welcome.subtitle"] = "Technical Analysis and Trading",
        ["welcome.notice.title"] = "IMPORTANT NOTICE",
        ["welcome.notice.1"] = "This software is intended solely for informational and entertainment purposes. The analyses, signals and recommendations provided do not constitute financial advice.",
        ["welcome.notice.2"] = "Trading cryptocurrencies involves significant risks. You may lose all of the capital you invest.",
        ["welcome.notice.3"] = "Any liability for financial losses arising from the use of this software is expressly excluded.",
        ["welcome.notice.4"] = "Always act on your own responsibility and only invest money you can afford to lose.",
        ["welcome.accept"] = "I have read and understood the notice",
        ["welcome.continue"] = "Continue",
        ["search.watermark"] = "Search...",
        ["scan.currency.tip"] = "Select trading currency (USD or EUR)",
        ["sort.direction"] = "A/Z",
        ["sort.direction.tip"] = "Reverse sort direction (ascending/descending)",
        ["strategy.applyfake"] = "Apply to paper portfolio now",
        ["strategy.autofake"] = "Trade automatically after each scan",
        ["strategy.autocalc"] = "Calculate strategy automatically",
        ["strategy.optimizing.note"] = "Use this as guidance, not as fully automatic learning.",
        ["strategy.applyoptimized"] = "Apply",
        ["strategy.load.saved.tip"] = "Select a saved strategy to load",
        ["portfolio.sort"] = "Sort by:",
        ["portfolio.exportpdf"] = "Export PDF",
        ["portfolio.resetview"] = "Reset View",
        ["portfolio.chart"] = "Portfolio Performance",
        ["portfolio.savepdf.title"] = "Save portfolio list as PDF",
        ["portfolio.savepdf.type"] = "PDF File",
        ["buy.dialog.title"] = "Buy Coin",
        ["sell.dialog.title"] = "Sell Coin",
        ["buy.mode.amount"] = "Coin amount",
        ["buy.mode.value"] = "Amount in currency",
        ["buy.amount.watermark"] = "Amount (e.g. 0.01)",
        ["buy.value.watermark"] = "Value (e.g. 500)",
        ["sell.amount.watermark"] = "Amount to sell",
        ["editblock.hint"] = "You can change the most important block logic here directly.",
        ["editblock.amount.hint"] = "Examples: 5%, 10%, 25%, 50%, 100% or All",
        ["editblock.operator.tip"] = "Comparison operator for the condition",
        ["editblock.value.watermark"] = "e.g. 30",
        ["editblock.preset.watermark"] = "e.g. Positive signal",
        ["editblock.alarm.watermark"] = "Signal detected",
        ["source.manual"] = "Manual",
        ["source.ai"] = "AI Trading",
        ["source.strategy"] = "Strategy",
        ["source.backtest"] = "Backtest",
        ["orderbook.strongbuy"] = "Strong Buying Pressure",
        ["orderbook.buy"] = "Buying Pressure",
        ["orderbook.neutral"] = "Neutral",
        ["orderbook.sell"] = "Selling Pressure",
        ["orderbook.strongsell"] = "Strong Selling Pressure",
        ["ti.rsi.oversold"] = "Oversold",
        ["ti.rsi.low"] = "Low",
        ["ti.rsi.neutral"] = "Neutral",
        ["ti.rsi.high"] = "High",
        ["ti.rsi.overbought"] = "Overbought",
        ["ti.macd.bullish"] = "Bullish",
        ["ti.macd.softbullish"] = "Slightly Bullish",
        ["ti.macd.bearish"] = "Bearish",
        ["ti.macd.softbearish"] = "Slightly Bearish",
        ["ti.bb.strongoversold"] = "Strongly Oversold",
        ["ti.bb.oversold"] = "Oversold",
        ["ti.bb.overbought"] = "Overbought",
        ["ti.bb.strongoverbought"] = "Strongly Overbought",
        ["ti.sma.golden"] = "Bullish (Golden Cross)",
        ["ti.sma.death"] = "Bearish (Death Cross)",
        ["ti.volume.above"] = "Above Average",
        ["ti.volume.below"] = "Below Average",
        ["strategy.block.start"] = "START",
        ["strategy.block.startdesc"] = "Entry point (1 output)",
        ["strategy.block.buy"] = "BUY",
        ["strategy.block.sell"] = "SELL",
        ["strategy.block.hold"] = "HOLD",
        ["strategy.block.alarm"] = "ALARM",
        ["strategy.block.buydesc"] = "Buy: {0}",
        ["strategy.block.selldesc"] = "Sell: {0}",
        ["strategy.block.holddesc"] = "Hold position",
        ["strategy.block.alarmdesc"] = "Notification",
        ["strategy.name.new"] = "New Strategy",
        ["strategy.action.detected"] = "Signal detected",
        ["buyzone.nobuy"] = "Do not buy",
        ["buyzone.now"] = "Now ({0})",
        ["buyzone.below"] = "Below {0}",
        ["strategy.action.buy"] = "Buy",
        ["strategy.action.sell"] = "Sell",
        ["strategy.action.hold"] = "Hold",
    };
}
